---
title: "Weather 2024"
author: "Maris Pärn"
editor: visual
---

## Exploration of weather data from MetNo

```{r setup}
#| echo: false
#| warning: false


library(tidyverse)
library(ggplot2)
library(dplyr)
library(lubridate)
library(MetBrewer)
library(hms)
library(zoo)
library(circular)
library(ggrepel)
library(openair)

```

```{r data}
#| echo: false
#| warning: false


weather <- read.csv("WeatherData2024.csv")
overview_summary <- read.csv("overview_2024.csv")

  # fix weather
  weather$X <- NULL
  weather$Unnamed..0 <- NULL
  weather$Unnamed..0.1 <- NULL

  
  weather <- na.omit(weather)
  
  summary(weather)
  
  

  
# make a list of hours that I have the data from and see if it matches the hours I have the weather data for
  


```

```{r interpolation}
#| echo: false
#| warning: false


 # for temperature, pressure, cloud area, humidity and wind speed, I'll use linear interpolation
  
  # create a column with datetime format
  
  weather <- weather %>%
    mutate(datetime = make_datetime(
      year = year,  
      month = month,
      day = day,
      hour = hour
    ))
  
  missing_time <- make_datetime(2024, 8, 20, 22)
  
  weather_full <- weather %>%
    group_by(name) %>%
    tidyr::complete(datetime = c(datetime, missing_time)) %>%
    ungroup()
  
  linear_vars <- c(
    "air_temperature_2m",
    "air_pressure_at_sea_level",
    "cloud_area_fraction",
    "relative_humidity_2m",
    "wind_speed_10m"
  )
  
  
  weather_full <- weather_full %>%
    group_by(name) %>%
    arrange(datetime) %>%
    mutate(across(
      all_of(linear_vars),
      ~ na.approx(., x = datetime, na.rm = FALSE)
    ))
  
  # for wind direction, I'll use circular interpolation
  
  weather_full <- weather_full %>%
    mutate(
      wd_rad = wind_direction_10m * pi / 180,
      u = sin(wd_rad),
      v = cos(wd_rad)
    )
  
  weather_full <- weather_full %>%
    group_by(name) %>%
    arrange(datetime) %>%
    mutate(across(
      c(u, v),
      ~ zoo::na.approx(., x = as.numeric(datetime), na.rm = FALSE)
    )) %>%
    ungroup()
  
  weather_full <- weather_full %>%
    mutate(
      wind_direction_10m =
        (atan2(u, v) * 180 / pi) %% 360
    ) %>%
    select(-wd_rad, -u, -v)
  
  # precipitation I'll assess based on the values before/after. It seems that the rain stopped before that timepoint, I'll add 0 to everything
  
  weather_full <- weather_full %>%
    mutate(
      precipitation_amount = if_else(
        is.na(precipitation_amount),
        0,
        precipitation_amount
      )
    )
  
  # fill other datarows that have NA-s
  
  weather_full <- weather_full %>%
    mutate(
      year  = year(datetime),
      month = month(datetime),
      day   = day(datetime),
      hour  = hour(datetime)
    )
  
  site_vars <- c("location_latitude", "location_longitude", "nearest_latitude", "nearest_longitude")
  
  weather_full <- weather_full %>%
    group_by(name) %>%
    fill(all_of(site_vars), .direction = "downup") %>%
    ungroup()
  
  # add type to weather 
  
  weather_full$type <- overview_summary$type[match(weather_full$name, overview_summary$Site)]

```

Here I'll see what the temperatures are like around my sites. We see some outliers, as CM-07 has lower mean temperature during the detector work times and CM-01 and Cm-02 have more stable temperatures as the only 2 locations further away in the sea.

```{r temperature}
#| echo: false
#| warning: false


weather_full_ns <- weather_full %>%
    arrange(desc(location_latitude)) %>%
    mutate(
      name = factor(name, levels = unique(name))
    )
  
  ggplot(weather_full_ns, aes(x = name, y = air_temperature_2m)) +
    geom_boxplot(outlier.alpha = 0.3) +
    theme_bw() +
    labs(x = "Site from N to S", y = "Temperature (°C)") +
    theme(axis.text.x = element_text(angle = 90))

  
  temp_summary <- weather_full %>%
    group_by(name) %>%
    summarise(
      mean_temp = mean(air_temperature_2m, na.rm = TRUE),
      sd_temp   = sd(air_temperature_2m, na.rm = TRUE)
    )
  
  temp_summary$type <- overview_summary$type[match(temp_summary$name, overview_summary$Site)]
  
ggplot(temp_summary, aes(mean_temp, sd_temp, label = name)) +
  geom_point(aes(colour = type)) +
  geom_text_repel(size = 3, max.overlaps = 50) +
  theme_classic() +
  labs(
    x = "Mean temperature",
    y = "Temperature SD"
  )

```

```{r wind}
#| echo: false
#| warning: false


  wind_summary <- weather_full_ns %>%
    group_by(name) %>%
    summarise(
      max_wind = max(wind_speed_10m, na.rm = TRUE),
      p95_wind = quantile(wind_speed_10m, 0.95, na.rm = TRUE)
    )
  
  wind_summary$type <- overview_summary$type[match(wind_summary$name, overview_summary$Site)]
  
  ggplot(wind_summary, aes(x = name, y = max_wind)) +
    geom_col(aes(fill= type)) +
    theme_classic() +
    labs(y = "Max wind speed (m/s)") +
    theme(axis.text.x = element_text(angle = 90))

```

```{r others}
#| echo: false
#| warning: false

  
ggplot(weather_full_ns, aes(x = name, y = cloud_area_fraction)) +
  stat_summary(fun = mean, geom = "point") +
  theme_bw() +
  labs(x = "Site from N to S", y = "Mean cloud coverage") +
  theme(axis.text.x = element_text(angle = 90))
  
  windRose(
    weather_full,
    ws = "wind_speed_10m",
    wd = "wind_direction_10m",
    facet = "name",
    ncol = 5
  )
  
  windRose(
    subset(weather_full, month %in% c(6,7)),
    ws = "wind_speed_10m",
    wd = "wind_direction_10m",
    facet = "name",
    ncol = 5
  )
  
    windRose(
    subset(weather_full, month %in% c(8)),
    ws = "wind_speed_10m",
    wd = "wind_direction_10m",
    facet = "name",
    ncol = 5
  )
  
  windRose(
    subset(weather_full, month %in% c(9)),
    ws = "wind_speed_10m",
    wd = "wind_direction_10m",
    facet = "name",
    ncol = 5
  )
  
    windRose(
    subset(weather_full, month %in% c(10)),
    ws = "wind_speed_10m",
    wd = "wind_direction_10m",
    facet = "name",
    ncol = 5
  )

mean_wind <- weather_full %>%
    group_by(name) %>%
    summarise(
      mean_wind = mean(wind_speed_10m, na.rm = TRUE)
    )

wind_summary$mean_wind <- mean_wind$mean_wind[match(wind_summary$name, mean_wind$name)]
  

 ggplot(wind_summary, aes(x = name, y = mean_wind)) +
    geom_col(aes(fill= type)) +
    theme_classic() +
    labs(y = "Mean wind speed (m/s)") +
    theme(axis.text.x = element_text(angle = 90))


```
```{r precipitation}

# put a threshold for rain (dataset has a lot of minuscle values)

rain_threshold <- 0.1

weather_full_ns <- weather_full_ns %>%
  mutate(
    rain_mm = if_else(
      precipitation_amount >= rain_threshold,
      precipitation_amount,
      0
    ),
    rain = precipitation_amount >= rain_threshold
  )

rain_freq <- weather_full_ns %>%
  group_by(name) %>%
  summarise(
    wet_frac = mean(rain, na.rm = TRUE)
  )

ggplot(rain_freq, aes(name, wet_frac)) +
  geom_col() +
  theme_bw() +
  labs(y = "Fraction of wet hours (≥ 0.1 mm)") +
  theme(axis.text.x = element_text(angle = 90))

ggplot(weather_full_ns) +
 aes(x = datetime, y = air_pressure_at_sea_level) +
 geom_line(colour = "#3A69BE") +
 labs(x = "Date", y = "Air pressure at sea level (hPa)", title = "Air pressure change over all the sites ") +
 theme_bw() +
 theme(legend.text = element_text(size = 12L), legend.title = element_text(size = 12L))

ggplot(weather_full_ns) +
 aes(x = datetime, y = air_temperature_2m) +
 geom_line(colour = "#3A69BE") +
 labs(x = "Date", y = "Temperature (°C)", title = "Temperature trend over 2024 season") +
 theme_bw() +
 theme(legend.text = element_text(size = 12L), legend.title = element_text(size = 12L))

ggplot(weather_full_ns) +
 aes(x = datetime, y = precipitation_amount, colour = type) +
 geom_point() +
 scale_color_hue(direction = 1) +
 labs(x = "Date", y = "Precipitation (mm)", title = "Amount of rainfall in 2024 field season", 
 color = "Category") +
 theme_bw() +
 theme(legend.text = element_text(size = 12L), legend.title = element_text(size = 12L))
```

